export const APP_CONSTANTS = {
  SALT_ROUNDS: 10,
  OTP_MAX_ATTEMPTS: 5,
  MAX_LOGIN_ATTEMPTS: 5,
  LOGIN_ATTEMPT_LOCKOUT_MS: 60000,
  JWT_ACCESS_EXPIRATION_TIME: '15m',
  JWT_REFRESH_EXPIRATION_TIME: '30d',
};
